on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifact_dir:
        required: false
        type: string
        default: "artifact"
      azure_webapp_name:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      azure_client_id:
        required: true
      azure_tenant_id:
        required: true
      azure_subscription_id:
        required: true
      gh_token:
        required: true

jobs:
  deploy_azure_web_app_job:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment_name }}

    steps:

      - name: artifact_download_webapp
        uses: actions/download-artifact@v8
        with:
          name: "${{ inputs.artifact_name }}"
          path: "${{ inputs.artifact_dir }}"

      - name: debug_artifact_dir
        continue-on-error: true
        shell: pwsh
        working-directory: "./${{ inputs.artifact_dir }}"
        run: |
          Get-ChildItem -Recurse

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: swa_token_add_mask
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "::add-mask::$(az staticwebapp secrets list -n ${{ inputs.azure_webapp_name }} | jq -r '.properties.apiKey')"            

      - name: swa_token_get
        uses: azure/CLI@v2
        with:
          inlineScript: |
            echo "SWA_TOKEN=$(az staticwebapp secrets list -n ${{ inputs.azure_webapp_name }} | jq -r '.properties.apiKey')" >> $GITHUB_ENV            

      - name: deploy_static_web_app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          repo_token: ${{ secrets.gh_token }}
          action: 'upload'
          app_location: ./${{ inputs.artifact_dir }}/wwwroot
          skip_app_build: true
          # deployment_environment: ${{ inputs.environment_name }}
